## This configuration was generated by terraform-provider-oci


resource "random_string" "redis_password" {
  length      = 24
  special     = false
  min_lower   = 2
  min_upper   = 2
  min_numeric = 4
}

resource "oci_redis_redis_cluster" "redis" {
  cluster_mode   = "NONSHARDED"
  compartment_id = var.compartment_id
  display_name   = var.display_name
  # freeform_tags = {
  # }
  node_count         = var.node_count
  node_memory_in_gbs = var.node_memory
  nsg_ids = [
  ]
  software_version = "VALKEY_7_2"
  subnet_id        = var.subnet_id
}

