## This configuration was generated by terraform-provider-oci


resource "random_string" "redis_password" {
  length      = 24
  special     = false
  min_lower   = 2
  min_upper   = 2
  min_numeric = 4
}

resource "oci_redis_redis_cluster" "redis" {
  cluster_mode   = "NONSHARDED"
  compartment_id = var.compartment_id
  display_name   = var.display_name
  # freeform_tags = {
  # }
  node_count         = var.node_count
  node_memory_in_gbs = var.node_memory
  nsg_ids = [
  ]
  software_version = "VALKEY_7_2"
  subnet_id        = var.subnet_id

  # force delete of the sec list that is created but not cleaned up
  # TODO make this work on local with api_key auth and profile
  provisioner "local-exec" {
    when = destroy
    on_failure = continue
    command = <<-EOT
set -x -o pipefail
export VCN_ID=$(oci network --auth instance_principal subnet get --subnet-id ${self.subnet_id} | jq -r '.data."vcn-id"')
export REDIS_SEC_LIST_ID=$(oci network security-list list --compartment-id ${self.compartment_id} --vcn-id $VCN_ID | jq -r '.data[] | select(."display-name" == "redis-security-list") | .id')
oci network security-list delete --security-list-id $REDIS_SEC_LIST_ID --force
EOT
  }
}

