apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata: 
  name: letsencrypt-staging
spec:
  acme:
    # profile, shortlived to be able to provision IP certs
    profile: shortlived
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef: 
      name: letsencrypt-issuer-staging-account-key
    solvers: 
    - http01:
        gatewayHTTPRoute:
          parentRefs:
          - name: langfuse
            namespace: langfuse
            sectionName: http
          labels:
            acme.cert-manager.io/http01-solver: "true"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata: 
  name: letsencrypt-prod
spec:
  acme:
    # profile, shortlived to be able to provision IP certs
    profile: shortlived
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef: 
      name: letsencrypt-issuer-prod-account-key
    solvers: 
    - http01:
        gatewayHTTPRoute:
          parentRefs:
          - name: langfuse
            namespace: langfuse
            sectionName: http
          labels:
            acme.cert-manager.io/http01-solver: "true"
