apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata: 
  name: letsencrypt-staging
  # namespace: cert-manager
spec:
  acme:
    # profile, shortlived to be able to provision IP certs
    profile: shortlived
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef: 
      name: letsencrypt-issuer-staging-account-key
    solvers: 
    - http01:
        ingress:
          ingressClassName: oci-native-ingress
          serviceType: ClusterIP
          ingressTemplate:
            metadata:
              annotations:
                oci-native-ingress.oraclecloud.com/http-listener-port: "80"
                oci-native-ingress.oraclecloud.com/https-listener-port: "443"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata: 
  name: letsencrypt-prod
  # namespace: cert-manager
spec:
  acme:
    # profile, shortlived to be able to provision IP certs
    profile: shortlived
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef: 
      name: letsencrypt-issuer-prod-account-key
    solvers: 
    - http01:
        ingress:
          ingressClassName: oci-native-ingress
          serviceType: ClusterIP
          ingressTemplate:
            metadata:
              annotations:
                oci-native-ingress.oraclecloud.com/http-listener-port: "80"
                oci-native-ingress.oraclecloud.com/https-listener-port: "443"
